spring:
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql8-container:3306/dbkt_microservice
    username: userdocker
    password: passworddocker
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect



#spring:
#  application:
#    name: product-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/dbkt_microservice
#    username: root
#    password: 08062002
##    url: ${SPRING_DATASOURCE_URL}
##    password: ${MYSQL_ROOT_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8085
